### ISSUE TITLE
BnHA movies, tmdbid and imdbid together

### ISSUE THREAD

**Issue by ablakers** [Anime-Lists/anime-lists#109]
RE:

```
  <anime anidbid="14776" tvdbid="305074" defaulttvdbseason="0" episodeoffset="6" tmdbid="" imdbid="">
    <name>Boku no Hero Academia the Movie - Heroes:Rising</name>
  </anime>
```

The TMDb ID is 592350 and the IMDb ID is tt11107074. I see the readme says tmdbid/imdbid should be a one or the other deal with preference going to imdbid, but what was the rationale behind that and is that still the case for the maintainers of this fork? I have found about 70 entries that have both a tmdbid _and_ an imdbid, including the first BnHA movie:

```
  <anime anidbid="13633" tvdbid="305074" defaulttvdbseason="0" episodeoffset="3" tmdbid="505262" imdbid="tt7745068">
    <name>Boku no Hero Academia the Movie: Futari no Hero</name>
  </anime>

```
and I'd have thought the more the merrier for sources for HAMA.

**Comment by sven-7** [comment]
Totally unsure on why. That was a legacy part of the readme from ScudLee. Perhaps that's a KODI issue? I imagine HAMA is fine taking both in. Best to ask @ZeroQI.

**Comment by ZeroQI** [comment]
The mapping file was for XBMC/Kodi anidb.net pluggin and I reused it. The IDs where for anidb and tvdb had insufficient data but can't remember for which field, could have to do with movies/OAV or hentai which tvdb lacked

If you have both entries it's new added entries I guess.
