### ISSUE TITLE
Missing Titles

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [Anime-Lists/anime-lists#111]
I noticed that a some shows are missing in the full-list while being in the name list.
E.g. Ancient Girl`s Frame (Id=16848). Is there some reason for this?

**Comment by reconman** [comment]
- `animetitles.xml` contains titles in all languages
- `anime-list-master.xml` is the main file used for mapping and contains all mapped and unmapped entries
- `anime-list.xml` only contains entries where the tvdbid, tmdbid or imdbid was filled.
- `anime-list-full.xml` only contains entries where the tvdbid has any value other than "".

In this case, nobody is really interested in mapping Chinese series. Usually, only classics and new seasonal Japanese Anime are mapped.
