### ISSUE TITLE
Incorrect TVDB mappings

### ISSUE THREAD

**Issue by secondsabre** [Anime-Lists/anime-lists#128]
Corrected a few series here, details enclosed.

Fushigi Yuugi OVAs: corrected anidbseason mapping and added explicit episode mapping

```
<anime anidbid="163" tvdbid="71444" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Fushigi Yuugi (1996)</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-1;2-2;3-3;</mapping>
    </mapping-list>
  </anime>
```
```
  <anime anidbid="164" tvdbid="71444" defaulttvdbseason="0" episodeoffset="3" tmdbid="" imdbid="">
    <name>Fushigi Yuugi: Dai Ni Bu</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-4;2-5;3-6;4-7;5-8;6-9;</mapping>
    </mapping-list>
  </anime>
```
```
  <anime anidbid="165" tvdbid="71444" defaulttvdbseason="0" episodeoffset="9" tmdbid="" imdbid="">
    <name>Fushigi Yuugi: Eikouden</name>
	<mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-10;2-11;3-12;4-13;</mapping>
    </mapping-list>
  </anime>
```

Patlabor: Mobile Police: corrected tvdbid

```
  <anime anidbid="1518" tvdbid="393352" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Patlabor: Mobile Police</name>
  </anime>
```

Slayers Excellent & Slayers Special: added explicit episode mapping since they're buried in the 'specials' and aren't mapping properly

```
  <anime anidbid="363" tvdbid="77681" defaulttvdbseason="0" episodeoffset="6" tmdbid="" imdbid="">
    <name>Slayers Excellent</name>
	<mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-7;2-8;3-9;</mapping>
    </mapping-list>
  </anime>
```
  
```
  <anime anidbid="155" tvdbid="77681" defaulttvdbseason="0" episodeoffset="2" tmdbid="" imdbid="">
    <name>Slayers Special</name>
	<mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-3;2-4;3-5;</mapping>
    </mapping-list>
    <supplemental-info>
      <studio>J.C.Staff</studio>
    </supplemental-info>
  </anime>
```

Weiss Kreuz Gluhen: corrected defaulttvdbseason

```
  <anime anidbid="226" tvdbid="72922" defaulttvdbseason="2" episodeoffset="" tmdbid="" imdbid="">
    <name>Weiss Kreuz Gluhen</name>
  </anime>
```

**Comment by sven-7** [comment]
Can you make a Pull Request with these changes?

**Comment by sven-7** [comment]
I'll try to get to it this week. It's not hard, but just make sure you follow the instructions on the readme.

**Comment by secondsabre** [comment]
Probably *the dumbest* of questions, but before I get too deep into committing the changes I think it's probably a good idea to take them for a test drive?

I notice in the agent logs for Hama there's a "local custom mapping file" (`anime_list_custom.xml`) that's marked as 'not found', and I figured I could stuff the code into that as an override for a local scan test run... but I can't figure out where that file goes? I tried creating it in `..\com.plexapp.agents.hama\DataItems\AnimeLists`, but running a metadata update resulted in the same 'not found' message.  Is that the correct location?  Is there a specific way to trigger it if it's added after the initial library build in Plex?

I know, ridiculous, but I couldn't find any specific reference in the documentation and the source code of Hama is beyond me. I'd appreciate any insight, and thanks in advance.

**Comment by BrutuZ** [comment]
> I notice in the agent logs for Hama there's a "local custom mapping file" (`anime_list_custom.xml`) that's marked as 'not found', and I figured I could stuff the code into that as an override for a local scan test run... but I can't figure out where that file goes? I tried creating it in `..\com.plexapp.agents.hama\DataItems\AnimeLists`, but running a metadata update resulted in the same 'not found' message. Is that the correct location? Is there a specific way to trigger it if it's added after the initial library build in Plex?


@secondsabre  For that purpose you're looking for `<<PlexDataFolder>>/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/AnimeLists/anime-list-corrections.xml`

**Comment by sven-7** [comment]
Yes - I would highly recommend doing that too. See if adding your entries in there gives the results that should be expected. If so, come back with results and I or another can make a pull request for you.

**Comment by secondsabre** [comment]
Couldn't get the `anime-list-corrections.xml` file to take either, but I split the difference and just ended  up manually editing the main list file with my corrections above to see how they flowed.

The Patlabor TV and Weiss Kreuz Gluhen maps worked okay (since it was just a straight edit of a season or TVDB ID), but all the episode mapping entries (Fushigi Yuugi, Slayers) still didn't seem to work. The correct series looks to have been pulled from AniDB but the episode names are still wrong; for some reason the scraper keeps pulling the episode titles from the first regular season, despite the `tvdbseason="0"` tags and the episode maps.  Not sure if I'm missing something in the format or syntax, but I'll keep messing around with it.  The format seems correct at a glance (comparing against the main wiki and other entries), but I'm probably missing something simple.

**Comment by BrutuZ** [comment]
Did you make sure to restart Hama between editing `anime-list-master.xml` and refreshing metadata for the entries on Plex? The plugin will only read the file on startup.

Also, there's no need for individual mappings on sequential episodes. Those are more for fine-tuning, like different order between AniDB and TVDB, Unmapping AniDB episodes not present on TVDB (Like the _Fushigi Yuugi (1996)_ entry did, for instance), TVDB having other entries between AniDB episodes, etc...

**Comment by secondsabre** [comment]
Pretty sure I restarted the plugin a few times, since the mappings for Weiss and Patlabor updated properly.

Both Fushigi Yugi and Slayers look to have the correct season/offset in the original file, but instead of using the S0 and EX offsets that are stated there, they keep pulling S1E1 titles and moving forward from there. I thought using explicit mapping might force them to the correct episodes since those episodes are listed as unique eps in S0 on TVDB, but no dice.

As an example, in Plex all four Fushigi Yugi series (main TV, plus three separate OAV series) all show:
Ep1: The Girl of Legend
Ep2: The Priestess of Suzaku
Ep3: The Seven Stars of Suzaku
Etc

Same goes for Slayers, Ep1 of the original TV series and Ep1 of both OAVs show "ANGRY? Lina's Furious Dragon Slave" despite the OAV entries being mapped to S0 with E offsets.

The series metadata itself is correct, with the synopsis and poster art reflecting the differences, but the episode metadata (screen cap, synopsis, title) just keeps pulling the same episodes over and over again, like it's ignoring the flags or not doing the math.

There's still a very real chance that I'm just doing something wrong, but I'm stumped as to a reason or solution.

**Comment by BrutuZ** [comment]
Since you seem to have the files in different folders per AniDB naming, did you tell ASS\Hama to use the `anidb2` mapping (https://github.com/ZeroQI/Absolute-Series-Scanner#forcing-the-movieseries-id)? It doesn't by default

**Comment by secondsabre** [comment]
OH MY GOSH I bet that's it.  Ugh, I knew I was doing something wrong.

Probably another stupid question though, but... where do I set that?  I see the readme explains how to tag individual folders/searches so they're recognized as such, but I assume there's a field in the HamaTV Agent/Library settings where I can set that globally?  I can't seem to find any settings for ASS in the Plex UI, and I don't see a "guid_type" field in the Hama agent settings, but probably just need to change one of those Advanced fields (like `T-EM 'title'`) from "anidb" to "anidb2"?  Would I be able to just do a refresh once that's changed, or would I have to unmatch/rematch/restart Plex/etc to get it to read?

**Comment by BrutuZ** [comment]
AFAIK there's no way to set secondary numbering by default.
Roughly, automatic matching will search TheTVDB and AniDB then pick the highest score above as a match (there's a little more logic involved but don't remember from the top of my head and am not by the computer so can't double check), but will set it as thetvdb or anidb, no 2-4 variants.

ASS has no UI at all, there's nothing to configure

The "advanced fields" on Hama are just the priority lists of whose metadata it will feed to Plex on a per-field basis.
Ex: Use series title from TheTVDB, summary from AniDB, Poster from AniList if available but fallback to TheTVDB otherwise, etc...

**Comment by BrutuZ** [comment]
Kind of forgot the main question since was replying on mobile and couldn't read your message while typing.
> Would I be able to just do a refresh once that's changed, or would I have to unmatch/rematch/restart Plex/etc to get it to read?

A refresh Metadata wouldn't change the ID, but a simple Fix Match would do, no need to unmatch or restart anything

**Comment by secondsabre** [comment]
I think I've just about cracked it, and thanks so much @BrutuZ for your help so far.  Sorry for being such a n00b and not realizing the `guid_type` was a factor.

I played around with using `anidb2/3/4` as the guid_type, and that seems to have corrected the episode names (BIG WIN), but now I've run into what I hope is the last problem; now that the episode names are populating properly, all the series titles have reverted to a single series.  Stock AniDB guid gave me individual series (with unique posters/synopsis/etc) but homogenized episodes, but now I'm dealing with the opposite, unique episodes w/ homogenized series.

I've made sure my metadata sources in the Hama settings are set to use `AniDB` as the primary for everything, but can't seem to get the best of both worlds (unique series entries w/ correct ep names)? Any final words of wisdom to help bend this system to my will/library structure?

**Comment by BrutuZ** [comment]
Only `anidb` ID will give what you're looking for (separate series), "everything else" is meant to convert into TVDB data that (mostly) uses seasons.

You could get a main series entry with seasons reflecting AniDB entries both in name and poster with `tvdb4` and [tvdb4.mapping.xml](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.mapping.xml) + [tvdb4.posters.xml](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.posters.xml)

**Comment by secondsabre** [comment]
Nice! Seems like a bit of fiddling, but should be doable.  To clarify, the readme says that `tvdb4` mapping is pulled from the Github repo first, and can be manually overridden with a plain-text `tvdb4.mapping` file inside the folder structure (specifies that this is not an XML file).  Is there a similar override file (XML or otherwise) that can be used for `tvdb4.posters.xml` per-directory?  If not, is there a location where I can create and drop global override XMLs that would append to (or replace) the default map from the repo?

**Comment by BrutuZ** [comment]
I don't know, never really used `tvdb4`, or anything other than `tvdb`, `anidb2` or `tvdb2` actually.
It's something to try out for yourself or maybe bring up on https://github.com/ZeroQI/Absolute-Series-Scanner

**Comment by secondsabre** [comment]
No worries, I'll do some digging. Thanks very much for all your help so
far, answered a ton a questions and got me way closer to a final solution.
Appreciate everything you've done here!
