### ISSUE TITLE
Heya Camp special needs a mapping to the TVDB order

### ISSUE THREAD

**Issue by dekarguy** [Anime-Lists/anime-lists#14]
The entry should be as follows in order to put the S1 episode in the proper spot in the TVDB entries
```
  <anime anidbid="14439" tvdbid="330692" defaulttvdbseason="0" episodeoffset="4">
    <name>Heya Camp</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-17;2-0;</mapping>
    </mapping-list>
  </anime>
```

**Comment by reconman** [comment]
I would appreciate it if you could open a PR next time. But please read about the edited [Contributing](https://github.com/Anime-Lists/anime-lists#contributing) steps first.

**Comment by dekarguy** [comment]
Awesome, thanks for the quick fix. The instructions still say opening an
issue is a valid avenue for updates.

**Comment by reconman** [comment]
I would interpret it the following way:
1. If you know what you're doing, create a PR
2. If you don't know what you're doing, ask for help using an Issue
