### ISSUE TITLE
Permission to use the anime lists

### ISSUE THREAD

**Issue by vosmiic** [Anime-Lists/anime-lists#143]
Hi

I would like to use the lists contained in this repo for an open-source Jellyfin plugin I am developing (https://github.com/vosmiic/jellyfin-ani-sync) to sync watched anime to multiple tracking providers (AniList, MAL and Kitsu at the moment).
Are you happy for me to use the lists in my plugin?
I can expand further my intended use of the lists contents if it would help.

Thanks

**Comment by BrutuZ** [comment]
While I can't speak officially, the list is openly available and maintained via community effort, so should be fine to use it as long as its credited. That also gives users of your implementation a way to contribute adding\fixing entry mappings.

**Comment by vosmiic** [comment]
Great, thanks. I just got a bit worried since it doesn't have a license and per [GitHub policy](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license=), that generally means no outside use is permitted by default.
I should have noted that I would add a link to this repo in the plugin repo. 
The more people we get to contribute to the project the better it is for everyone.
