### ISSUE TITLE
Incorrect mapping for Fate/Stay Night: Heaven's Feel (2017),(2019),(2020)

### ISSUE THREAD

**Issue by toastard** [Anime-Lists/anime-lists#162]
```
<anime anidbid="10755" tvdbid="79151" defaulttvdbseason="0" episodeoffset="5" tmdbid="283984,390634,390635" imdbid="tt4054952,tt8091892,tt8092118">

<name>Gekijouban Fate/Stay Night: Heaven's Feel</name>

</anime>
```

Gekijouban Fate/Stay Night: Heaven's Feel movie trilogy is pulling the tvdbid 79151 from Fate/Stay Night 2006 TV series. 

Please see the current mapping below:
https://thetvdb.com/series/fate-stay-night
https://anidb.net/anime/10755

I believe the correct tvdbid should be 8668, 41 and 5327 respectively. Or just 8668 to fix the episodic metadata.
https://thetvdb.com/movies/fatestay-night-heavens-feel-i-presage-flower
https://thetvdb.com/movies/fatestay-night-heavens-feel-ii-lost-butterfly
https://thetvdb.com/movies/fatestay-night-heavens-feel-iii-spring-song

Screenshot from Plex.
https://i.imgur.com/1Z9SAgK.jpg

**Comment by BrutuZ** [comment]
Intended, only series are supported from TVDB. For movies there's bothTMDB and IMDB to pick from


-------- Original message --------
From: toastard ***@***.***>
Date: 8/21/22 18:02 (GMT-03:00)
To: Anime-Lists/anime-lists ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Anime-Lists/anime-lists] Incorrect mapping for Fate/Stay Night: Heaven's Feel (2017),(2019),(2020) (Issue #162)


`

Gekijouban Fate/Stay Night: Heaven's Feel

`

Gekijouban Fate/Stay Night: Heaven's Feel movie trilogy is pulling the tvdbid 79151 from Fate/Stay Night 2006 TV series.

Please see the current mapping below:
https://thetvdb.com/series/fate-stay-night
https://anidb.net/anime/10755

I believe the correct tvdbid should be 8668, 41 and 5327 respectively. Or just 8668 to fix the episodic metadata.
https://thetvdb.com/movies/fatestay-night-heavens-feel-i-presage-flower
https://thetvdb.com/movies/fatestay-night-heavens-feel-ii-lost-butterfly
https://thetvdb.com/movies/fatestay-night-heavens-feel-iii-spring-song

Screenshot from Plex.
https://i.imgur.com/1Z9SAgK.jpg

**Comment by BrutuZ** [comment]
They probably were mapped under specials and got removed after TVDB changed their policy to no longer allow anime movies and full length OVAs under specials to favour their movies database.

**Comment by toastard** [comment]
Thanks for the quick response. I guess there's no way to map movies from TVDB? That's a bummer.

**Comment by BrutuZ** [comment]
Unfortunately no, same goes for TMDB series.
Both services decided to expand beyond their original namesake focus and the list didn't keep up.
I believe TMDB series was implemented into HAMA to some extent (I think it just fetches manually specified IDs, no search or list referencing), but never read about any support for TVDB movies

**Comment by toastard** [comment]
My apologies for reopening the issue but I just thought of an idea. Can we treat this as a movie instead of a series? Changing tvdbid="movie" would prevent it from pulling the 2006 series metadata and will ensure the one for 10755 is left intact (especially the main cast, description, background, release etc.) This way all you need to do is link all 3 movies to 10755 and they should all populate to the main title.

I'm thinking of something like this:

```
  </anime>
  <anime anidbid="10755" tvdbid="movie" defaulttvdbseason="1" imdbid="tt4054952,tt8091892,tt8092118">
    <name>Fate/Stay Night: Heaven's Feel</name>
  </anime>
```

or


```
  </anime>
  <anime anidbid="10755" tvdbid="movie" defaulttvdbseason="1" imdbid="tt4054952">
    <name>Fate/Stay Night: Heaven's Feel</name>
  </anime>
```

**Comment by BrutuZ** [comment]
Sure is, in fact `tvdbid=movie` is the correct way to map movies that aren't also mapped as series' specials, as this one once was.
Just bear in mind that HAMA just uses the first ID though, if you want it to display correctly you **must** specify the ID for each of them manually, either via https://github.com/ZeroQI/Absolute-Series-Scanner#forcing-the-movieseries-id or inside Plex

**Comment by toastard** [comment]
Hmm it's strange but I've already forced it manually through both the ID naming and Plex.
Plex shows that it matches 100% with anidb 10755. The issue only occurs when going into the title and finding that the 79151 data is being pulled from tvdbid. Unless there's another way I can omit it without removing TheTVDB completely?

**Comment by toastard** [comment]
No luck on my end. I don't quite get it but this seems to be affecting some people here as well. Not sure if the tvdbid is somehow overriding the anidb data.
https://old.reddit.com/r/PleX/comments/r6irf1/fate_anime_movies_heavens_feel_trilogy_populating/

**Comment by BrutuZ** [comment]
Did you edit or delete the HAMA copy of `anime-list-master.xml`? HAMA only updates it every 6 days. By default it is in `<Plex Data Folder>\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AnimeLists`
I edited that copy before scanning the files on the video

**Comment by toastard** [comment]
Oops that's my bad, I didn't know the master list was updated. Finally got it to load the proper screen, thanks for the help!
