### ISSUE TITLE
Encouragement of Climb OVA and question about mapping ova to tvdb season 0 properly

### ISSUE THREAD

**Issue by Boontato** [Anime-Lists/anime-lists#189]
So for 
<anime anidbid="13206" tvdbid="" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="">
    <name>Yama no Susume: Omoide Present - Natsu: Kokona no 8/31 / Aki: Hinata no 10/28</name>

tvdbid should be 264523 in s00e04 but i can't get it to show up there.  it keeps going to the very end at s02e25.
tried using the defaulttvdbseason=0 and episodeoffset=3 and it still did not want to cooperate.
wondering if theres a way to do it or a proper way to do it in anime-list.master.xml. i'm new to this but wanting to help and contribute.

reference below.
https://anidb.net/anime/13206
https://thetvdb.com/index.php?tab=series&id=264523

**Comment by Boontato** [comment]
wait nevermind it was my fault using an incorrect anidb# in ASS

**Comment by BrutuZ** [comment]
Setting these 3 values should be enough.
Are you positive it is not an agent or scanner issue?

**Comment by Boontato** [comment]
absolutely my fault, i was setting that entry as anidb3 and i went to read what that actually does on ASS, i should've been using anidb2 to make it go to season 0. I am getting the hang of this!
