### ISSUE TITLE
[MAP] Cyberpunk: Edgerunners

### ISSUE THREAD

**Issue by NADESHIKON** [Anime-Lists/anime-lists#197]
### Anime Title

Cyberpunk: Edgerunners

### AniDB ID

15610

### TVDB ID

384541

### Season Number

1

### Is there an existing issue for this?

- [X] I have searched the existing issues and pull requests

**Comment by BrutuZ** [comment]
Mapped on 09c13c032cc0a3f2c15aaf0dc1e6999ee3e6aa96
