### ISSUE TITLE
AniDB ID 10143 is mapped incorrectly to TVDB ID.

### ISSUE THREAD

**Issue by varoOP** [Anime-Lists/anime-lists#264]
It's mapped to "music video" instead of a proper ID.

**Comment by BrutuZ** [comment]
Which would be... ?

**Comment by varoOP** [comment]
I do not think it has a TVDB ID. It's a single music video

**Comment by BrutuZ** [comment]
Then it is correct: https://github.com/Anime-Lists/anime-lists/blob/master/README.md#anime-list-masterxml-1

> **tvdbid** - theTVDB.com id. Multi-episode titles not found on theTVDB.com are marked as "unknown", as they may eventually get added and this makes it easier to re-check (via anime-list-unknown.xml). ***One-off titles that won't ever be added to theTVDB.com (movies, TV specials, one-shot OVAs) are marked by their AniDb.net type, unless they can be associated to a multi-episode series (in which case they use the corresponding theTVDB.com id or "unknown").***
>
> Pornographic titles are marked by "hentai" regardless of episode count as they will never appear on theTVDB.com.
