### ISSUE TITLE
[MAP] That Time I Got Reincarnated as a Slime the Movie - Scarlet Bond

### ISSUE THREAD

**Issue by EndOfLine369** [Anime-Lists/anime-lists#295]
### Anime Title

Gekijouban Tensei Shitara Slime Datta Ken: Guren no Kizuna Hen

### AniDB ID

16776  https://anidb.net/anime/16776

### TVDB ID

352408  https://thetvdb.com/series/that-time-i-got-reincarnated-as-a-slime

### Season Number

S00E09  https://thetvdb.com/series/that-time-i-got-reincarnated-as-a-slime/seasons/official/0

### Is there an existing issue for this?

- [X] I have searched the existing issues and pull requests

**Comment by BrutuZ** [comment]
Oh?! I didn't expect it to be added to specials after TVDB changed the policy on movies. Pleasantly  surprised, especially since the entry was created by a mod.

**Comment by EndOfLine369** [comment]
Could be on old tvdb entries that existed before the new policy are still allowed the movies to still be added as specials.....

**Comment by BrutuZ** [comment]
Doesn't seem like it. I suspect the ruling is even older than the movie (over a year now), and even then the entry's created and modified dates are both from a couple weeks ago.

Could also be that TVDB went back on that decision or made up some weird exception like having a TV release. Either way, there's an official entry so I won't complain 😃

**Comment by EndOfLine369** [comment]
Was talking about the TV series entry age. And yeah, doesn't really matter why the entry it exists. It's there, lets use it 😄.
