### ISSUE TITLE
"91 Days" specials mapping

### ISSUE THREAD

**Issue by ZeroQI** [Anime-Lists/anime-lists#30]
https://github.com/ZeroQI/Hama.bundle/issues/439

Thetvdb s00e01 is called 'Brief Candle' https://thetvdb.com/series/91-days/episodes/5704266
AniDB s00e01 is shoal of times, s01e02 is 'Brief Candle' https://anidb.net/anime/12014
Sven7's fork of ScudLee's AnimeList: https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-master.xml
```
  <anime anidbid="12014" tvdbid="309530" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>91 Days</name>
  </anime>
```
Specials are not mapped and the first two specials are swapped between anidb and TheTVDB
```
  <anime anidbid="12014" tvdbid="309530" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>91 Days</name>
      <mapping anidbseason="0" tvdbseason="0">;1-2;2-1;3-3;4-4;5-5;6-6;7-7;8-8;9-9;</mapping>
  </anime>
```

**Comment by sven-7** [comment]
This can be closed now. I merged it into the master.
