### ISSUE TITLE
[MAP] <Mushoku Tensei: Jobless Reincarnation>

### ISSUE THREAD

**Issue by Boontato** [Anime-Lists/anime-lists#324]
### Anime Title

Mushoku Tensei: Jobless Reincarnation season 2

### AniDB ID

17236

### TVDB ID

371310

### Season Number

0

### Is there an existing issue for this?

- [X] I have searched the existing issues and pull requests

**Comment by Boontato** [comment]
I am not exactly sure how to fix it with maping-list but season 1 cour 2 has the s00e01 Eris the Goblin Slayer
season 2 has a season s00e02 which on anidb is episode 0

**Comment by BrutuZ** [comment]
On AniDB it's Special (Season 0 for the list purposes) 1, in which case you just mimic the S2 special mapping style
```xml
   <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-2;</mapping>
    </mapping-list>
```
Assuming AniDB S1 = TVDB S00E02

**Comment by Boontato** [comment]
ah gotcha, i was just confused since there was extra things like start and end and offset, i guess thats related to creditless stuff thats on anidb and not tvdb

**Comment by BrutuZ** [comment]
Start and End means the offset will only apply to that interval.
If you're curious, Readme has those and more parameters detailed 😉
