### ISSUE TITLE
linking for Gekijouban Mahouka Koukou no Rettousei: Hoshi o Yobu Shoujo is incorrect

### ISSUE THREAD

**Issue by CommanderBubble** [Anime-Lists/anime-lists#334]
the movie is an entirely separate entrty on [TVDB.com](https://thetvdb.com/movies/the-irregular-at-magic-high-school-the-girl-who-calls-the-stars#general) - it has a movie ID (27507) not a series ID.

it is not listed as an episode under the main series to link it to, and as such, i've not been able to figure out what to mark it as in `anime-list-master.xml` to get it to correctly identify.

i've tried "movie", removing the series id entirely, but no matter what, it will always show up a separate match, with the correct top level data, but an incorrect episode summary, and is unable to link to the parent series

**Comment by BrutuZ** [comment]
Seems TVDB mods had a fit and cleaned up all full-length from the Specials season for this show.
They'd done it with the last one ([Reminiscence Arc](https://anib.net/a16081)) already, now they're all gone. Not much to do but leave the list as `tvdbid=movie` and\or open a support ticket on TVDB to reinstate these under the locked specials season with their new system that directly cross-references the movie entry
