### ISSUE TITLE
Silver Spoon doesn't get matched unless it's called by japanese name (Gin no Saji)

### ISSUE THREAD

**Issue by CommanderBubble** [Anime-Lists/anime-lists#335]
unsure why, it will incorrectly match to another tv series also called [Silver Spoon](https://thetvdb.com/series/major-2014) when more than 1 season exists. it's reproducible with empty files, even with the anidb.id files present.

if only the first season is present, then the match is correct. however if there is anything in a season 2 folder, then it will incorrectly match to the listed one above. the entries in the master list are all correct, so i'm unsure as to why this would be happening

**Comment by BrutuZ** [comment]
If the list entries are correct it sounds like an issue for the HAMA/ASS (or whatever else is using the list) repos instead
