### ISSUE TITLE
Mapping half-length episodes

### ISSUE THREAD

**Issue by winterbird-code** [Anime-Lists/anime-lists#339]
I noticed that some episodes are mapped one-to-many using the syntax `;1-1+2;`; for example [Gera Gera Booth Monogatari](https://anidb.net/anime/2737) for which thetvdb has [half lenght episodes](https://thetvdb.com/series/ox-tales/seasons/official/1). I couldn't find any many-to-one mapping though. I noticed this when I wanted to map [Ling Qi](https://anidb.net/anime/12656), which has half-length episodes in anidb, but [full length in thetvdb](https://thetvdb.com/series/spiritpact/seasons/official/1). Would this be a correct mapping, or would it break stuff horribly:

```
  <anime anidbid="12656" tvdbid="321503" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Ling Qi</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="1">;1+2-1;3+4-2;5+6-3;7+8-4;9+10-5;11+12-6;13+14-7;15+16-8;17+18-9;19+20-10;</mapping>
    </mapping-list>
  </anime>
```

Maybe this syntax should be mentioned in the README as well?

**Comment by BrutuZ** [comment]
I don't think that syntax is supported by any client and I'm not sure it wouldn't break any of them either.
On the [very] few instances I encountered this, I either pick a single episode to map (`;1-1;3-2;5-3;...`) or map them all to the same (`;1-1;2-1;3-2;4-2;5-3;6-3;...`), whichever compromise worked best for the situation.

**Comment by winterbird-code** [comment]
Hmm, I like the second, more explicit, mapping better since you otherwise wouldn't know how to map episode 2 and 4 and so on. I'll prepare a PR for readme and the Ling Qi mapping.
