### ISSUE TITLE
Akatsuki no Yona (2015) [anidb-11143] [tvdb-283942]

### ISSUE THREAD

**Issue by ZeroQI** [Anime-Lists/anime-lists#34]
Raised through https://github.com/ZeroQI/Hama.bundle/issues/443

XML mapping [https://raw.githubusercontent.com/Anime-Lists/anime-lists/master/anime-list-master.xml]
```
  <anime anidbid="11143" tvdbid="283942" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Akatsuki no Yona (2015)</name>
  </anime>
```

Looking at episode mapping manually:
- tvdb https://thetvdb.com/series/yona-of-the-dawn/allseasons/official
- anidb https://anidb.net/anime/11143
- mapping: anidb s01e01-03, s00e01 =>tvdb s00e01-03, s00e04

Mapping file is wrong in mapping file, s00e01 should map to s00e04, it should be the below:
```
  <anime anidbid="11143" tvdbid="283942" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Akatsuki no Yona (2015)</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-4;</mapping>
    </mapping-list>
  </anime>
```

**Comment by sven-7** [comment]
Merged. Closing.
