### ISSUE TITLE
[MAP] The Eminence in Shadow Season 2 Specials

### ISSUE THREAD

**Issue by Boontato** [Anime-Lists/anime-lists#408]
### Anime Title

Kage no Jitsuryokusha ni Naritakute! 2nd Season

### AniDB ID

17877

### TVDB ID

407520

### Season Number

0

### Is there an existing issue for this?

- [X] I have searched the existing issues and pull requests

**Comment by Boontato** [comment]
don't want to mess things up but theres season 2 specials called Kage-Jitsu that picks up from season 1 specials.

**Comment by BrutuZ** [comment]
Issue instead of PR? What happened? 😦
