### ISSUE TITLE
attack on titan movies

### ISSUE THREAD

**Issue by fawzib** [Anime-Lists/anime-lists#41]
https://anidb.net/anime/10583

should map to:

https://thetvdb.com/movies/attack-on-titan-crimson-bow-and-arrow
https://thetvdb.com/movies/attack-on-titan-the-wings-of-freedom

**Comment by sven-7** [comment]
@reconman I don't think we map to TheTVDB movies. Right? This is mapped to the correct specials already.

**Comment by fawzib** [comment]
movies should not be in specials otherwise the normal plex scrapper will be fine.

**Comment by reconman** [comment]
So far, no entry is mapped to a TVDB movie. In fact, many entries have `tvdbid="movie"` set to indicate that there will never be a TVDB entry.

I saw some message by a TVDB admin that movies should not be specials, but people still do it.

I can't tell how Hama will react to linking to a movie, especially if your episode is already using the S00E file name format. I don't want to break existing logic.

Will have to experiment to find out.

**Comment by fawzib** [comment]
so what is the logic behind not mapping a movie to tvdbid?

**Comment by reconman** [comment]
You'd have to ask Scudlee, who disappeared into thin air.

The main question is: Why do you want to link to the TVDB movie entries?

**Comment by sven-7** [comment]
I'm also not sure if @zeroqi's HAMA and ASS would break if we did that.

**Comment by fawzib** [comment]
in the example above we have 3 attack on titan movies. 2 are in one anidb and the other is separate. all are compilations for example.

another example is Re: zero
we have 2 special series with multiple seasons merged into one anidb (11370)
Re:Petit - Re: Starting Life in Another World from Petit 
Re:Zero - Starting Break Time from Zero

each should map to a different tvdb series.

we should start mapping movies to tvdb and not to specials. keep the series clean, this is why we have collections

**Comment by ZeroQI** [comment]
ScudLee created the anidb.net agent for XBMC and the XML for mapping episode summaries from TheTVDB if i recalled well
- There is a Movie collection ONLY as Kodi/XBMC didn't allow series collections while Plex does...
- TheMovieDB did only movies at the time
- TheTVDB did only series at the time...
- TheTVDB movies started last year and are not supported by the HAMA agent yet as i would need to code TheTVDBv3.py for the new API... 

> we should start mapping movies to tvdb and not to specials. keep the series clean, this is why we have collections
- We do have collections, and also collection field auto creation for grouping folders with "local" metadata source for 'collection' HAMA setting (quite like the simplicity), or the movie collection increased with anidb related anime...
- A movie should not be mapped to TheTVDB specials according to theTVDB rules and knowing they support movies now, it makes sense
- Movie will be mapped to TheTVDB but doesn't mean HAMA or even Anime-Lists has to support it, as HAMA code is already complex. It does support TheMovieDb movies [tmdb-xxxx] and TheMovieDb series [tsdb-xxxx] already, so why reinvent the wheel? HAMA am not going to support Th

This should be a pure AniDB entry for HAMA: Gekijouban Shingeki no Kyojin [anidb-10583]/s01e01-02
- https://anidb.net/anime/10583

This should be a pure AniDB entry for HAMA: Re:Zero - Starting Life in Another World [anidb-11370] s00e02-26
- https://www.thetvdb.com/series/re-zero-starting-life-in-another-world/allseasons/official show TheTVDB consider them specials
- https://anidb.net/anime/11370 show AniDB consider them specials
- If TheTVDB consider them specials (and i agree), they should prevent the creation of separate series entries. These are chibi style versions of the characters in SHORTS aired after each episode, if that is not a special, i don't know what is...

If you want to keep the series clean, don't download chibi short for the series maybe?
You want to map every single anime movie to thetvdb movie when HAMA has no support coded for V3 API?
In theory, we could have another mapping file from anidb to thetvdb movie, but why should we? Which tvdb or anidb numbering to use? HAMA does anidb by default so it would gather metadata, so why double the complexity for Movies?
