### ISSUE TITLE
[MAP] Dr. Stone Season 3

### ISSUE THREAD

**Issue by PythonCoderAS** [Anime-Lists/anime-lists#414]
### Anime Title

Dr. Stone

### AniDB ID

17053

### TVDB ID

355774

### Season Number

3

### Is there an existing issue for this?

- [X] I have searched the existing issues and pull requests

**Comment by PythonCoderAS** [comment]
Dr Stone has a 3rd season, but it's the fourth entry as there is a "movie" special right before Season 3 that is part of the story. This is counted as a Special in TVDb.

**Comment by BrutuZ** [comment]
I don't understand what's the issue.

Ryuusui's and previous season's intermission episodes are already mapped under specials.
Season 3 (New World) was a split-cour, it has two entries but their episodes are properly mapped to Season 3.

**Comment by PythonCoderAS** [comment]
> I don't understand what's the issue. Ryuusui's and previous season's intermission episodes are already mapped under specials. Season 3 (New World) was a split-cour, it has two entries but their episodes are properly mapped to Season 3.

The Jellyfin Ani Sync plugin seems to think Season 3 is the Ryuusei special, so I figured it would have to be a data problem.

**Comment by BrutuZ** [comment]
I have them identified as expected on Plex+HAMA/ASS, so it seems like a client-side issue.
