### ISSUE TITLE
[MAP] Initial D: Battle Stage 3

### ISSUE THREAD

**Issue by acomick** [Anime-Lists/anime-lists#456]
### Anime Title

Initial D: Battle Stage 3

### AniDB ID

16380

### TVDB ID

157504

### TMDB ID (Only for movies)

827669

### IMDB ID (Only for movies)

tt15411068

### Is there an existing issue for this?

- [X] I have searched the existing issues and pull requests

**Comment by acomick** [comment]
Currently unmapped
  <anime anidbid="16380" tvdbid="" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="">
    <name>Initial D Battle Stage 3</name>
  </anime>

**Comment by BrutuZ** [comment]
That's a TVDB Movie ID, those don't go into the list. It should be `70900` for https://thetvdb.com/series/initial-d/episodes/8323359
