### ISSUE TITLE
[MAP] A Nobody’s Way Up to an Exploration Hero

### ISSUE THREAD

**Issue by ppkhoa** [Anime-Lists/anime-lists#462]
### Anime Title

Mob kara Hajimaru Tansaku Eiyuutan

### AniDB ID

18358

### TVDB ID

443862

### Season Number

1

### Is there an existing issue for this?

- [ ] I have searched the existing issues and pull requests

**Comment by BrutuZ** [comment]
Already mapped 2 weeks ago on #460
https://github.com/Anime-Lists/anime-lists/blob/7e3453090f236dd3624aeef67c053f919f22c26d/anime-list-full.xml#L38225-L38227
