### ISSUE TITLE
Nanoha mappings

### ISSUE THREAD

**Issue by Ondalf** [Anime-Lists/anime-lists#48]
Noted few errors and apparently my library just went haywire for this part (custom override got overriden lol), so:
```
  <anime anidbid="9788" tvdbid="81115" defaulttvdbseason="0" episodeoffset="" tmdbid="432057" imdbid="">
    <name>Magical Girl Lyrical Nanoha Reflection</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-99;2-99;3-99;4-99;5-99;6-99;</mapping>
      <mapping anidbseason="1" tvdbseason="0">;1-13;</mapping>
    </mapping-list>
  </anime>
  <anime anidbid="12264" tvdbid="81115" defaulttvdbseason="5" episodeoffset="" tmdbid="" imdbid="">
    <name>ViVid Strike!</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-99;2-15;3-16;4-17;</mapping>
    </mapping-list>
  </anime>
  <anime anidbid="13301" tvdbid="81115" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Magical Girl Lyrical Nanoha Detonation</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-14;</mapping>
    </mapping-list>
  </anime>
```
[TVDB Season 0](https://www.thetvdb.com/series/magical-girl-lyrical-nanoha/seasons/official/0) - AniDB [9788](https://anidb.net/a9788) [12264](https://anidb.net/a12264) [13301](https://anidb.net/a13301)
So, movies (detonation and reflection) were pointing originally to 16, 17 and vivid strikes specials to 13, 14 and 15.
This swaps them around and metadata gets collected just fine. Would be nice to get these fixed in main list...

**Comment by reconman** [comment]
Mapping multiple entries to special 99 won't work, since Hama can only use 1 AniDB entry metadata, it can't combine them.

So if you have S00E99 in your library, it will pick a random AniDB episode.

**Comment by reconman** [comment]
So a few things:

1. TVDB special 99 doesn't even exist, why are you mapping to it?
2. Vivid Strike is not only season 5 of Nanoha, but also has a seperate TVDB entry https://www.thetvdb.com/series/vivid-strike. Only in the seperate entry, S00E04 "Vivid Xmas" exists. Your special mappings for Vivid Strike are off by 1.

**Comment by Ondalf** [comment]
1. Oh, those mapping entries were taken directly from master list quite a while ago, so pardon if there was something weird in them. Only modifications I did were the ones I wrote under the entry... So bad copypaste as you could expect.
2. How would you go adding that entry as Nanoha S5 then, since it technically still is part of the show, and totally don't want Vivid Strike! to be part of own entity in the listing?
Ah indeed, Vivid Xmas is a thing and its missing from Nanoha TVDB entry.

So, follow ups: where should non-TVDB existing entries should be linked into? 0? thought of using 99 since when using Plex with AMSA, OPs start from 100 (or was it 150), so pushing the possible entries (which i don't even have) to 99 sounded like solid plan for a while.
Should've spent few more minutes creating those entries apparently... Main thing (for me) was to get the movies to proper spot.

**Comment by reconman** [comment]
0 is used if the TVDB episode does not exist.

**Comment by reconman** [comment]
Oh and I created Vivid Xmas on TVDB.
