### ISSUE TITLE
Issue with Mapping on anidb-10743

### ISSUE THREAD

**Issue by vyressi** [Anime-Lists/anime-lists#74]
The TVDB has changed the order of the Dragonball movies, others may also need correcting, but 10742 needs to be changed to offset 26 instead of 23
```
29449 <anime anidbid="10742" tvdbid="81472" defaulttvdbseason="0" episodeoffset="26" tmdbid="" imdbid="tt3819668">
29450    <name>Dragon Ball Z: Fukkatsu no "F"</name>
29451    <mapping-list>
29452      <mapping anidbseason="0" tvdbseason="0">;1-0;2-0;3-0;4-0;</mapping>
29453    </mapping-list>
29454  </anime>
```
Would have just done a pull request but no access, sorry to be a pest and post it as an issue lol

**Comment by reconman** [comment]
What do you mean by "no access"?

You would have to do the change on your fork and then create the PR from your fork to this repository.

**Comment by vyressi** [comment]
> What do you mean by "no access"?
> 
> You would have to do the change on your fork and then create the PR from your fork to this repository.

My bad, I'm used to working on my own repos annnnd I haven't slept yet, mainly because this issue was bugging the hell out of me.  Thanks for letting me know the proper procedure.

**Comment by vyressi** [comment]
I think I did that properly, i'm going to get some sleep, thanks again for the advice!
