### ISSUE TITLE
Incorrect tvdbid

### ISSUE THREAD

**Issue by Fribb** [Anime-Lists/anime-lists#98]
In some instances, the `tvdbid` is not an ID but rather `movie`.

Examples:
```
  <anime anidbid="7" tvdbid="movie" defaulttvdbseason="1" imdbid="tt0119698">
    <name>Mononoke-hime</name>
  </anime>
```
or
```
  <anime anidbid="28" tvdbid="movie" defaulttvdbseason="1" imdbid="tt0094625">
    <name>Akira</name>
  </anime>
```

**Comment by reconman** [comment]
Because Hama can only match against TVDB series, not movies.

**Comment by Fribb** [comment]
So this project is more specifically for HAMA instead of something more universal?

**Comment by reconman** [comment]
It was once used for Kodi, but nowadays I only know of Hama and ASS using it extensively.
