### ISSUE TITLE
Incorrect Mapping

### ISSUE THREAD

**Issue by meisnate12** [Anime-Lists/anime-lists#99]
```xml
  <anime anidbid="7508" tvdbid="79525" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Code Geass: Boukoku no Akito</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-0;2-0;3-0;4-0;</mapping>
      <mapping anidbseason="1" tvdbseason="0">;1-25;2-28;3-32;4-34;5-36;</mapping>
    </mapping-list>
  </anime>
```

The entry above should have the `imdbid="tt3354096,tt3354254,tt3354302,tt3354306,tt5920384"`

**Comment by reconman** [comment]
Multiple ids don't work.

**Comment by reconman** [comment]
I know that there are old entries with multiple set.

**Comment by meisnate12** [comment]
my program [Plex Meta Manager](https://github.com/meisnate12/Plex-Meta-Manager) relies on having the imdb_ids for movies and sets of movies because thats how i tell if the id is a movie or set of movies and get their ids. Like you said the list does this in other places is there any reason we cant still also do it going forward my users and I rely on this list heavily for Anime management

**Comment by meisnate12** [comment]
is there another way to include multiple movie ids either imdb or tmdb also id be willing to put in the work to clean up the ids. Is there a reason for all the unknown ids vs blank i would assume the unknown just isnt needed. Ultimately I'd prefer to switch ids for anime movies to primarily use tmdb ids because we as the community can add to tmdb much easier then imdb. I'd be more then willing to put in the work to change all the ids if its something youd be interested in.
